import type { CircuitGate } from "@/store/circuitStore"
import type { InitialStateId } from "@/lib/quantum/simulator"

export type LearningKind = "protocol" | "algorithm"
export type SupportLevel = "implemented" | "demo" | "stub"

export interface LearningExperience {
  id: string
  label: string
  kind: LearningKind
  accent: string
  summary: string
  support: SupportLevel
  nQubits: number
  initialStates?: InitialStateId[]
  gates: Omit<CircuitGate, "id">[]
  story: string[]
}

const tau = Math.PI * 2

export const LEARNING_EXPERIENCES: LearningExperience[] = [
  {
    id: "bb84",
    label: "BB84",
    kind: "protocol",
    accent: "#00d4ff",
    summary: "Prepare, send, measure, and sift a secret key while revealing eavesdropping through QBER.",
    support: "implemented",
    nQubits: 2,
    initialStates: ["|+⟩", "|0⟩"],
    gates: [
      { gateId: "H", qubit: 0, step: 0 },
      { gateId: "CHANCE", qubit: 0, step: 1 },
      { gateId: "MEASURE", qubit: 0, step: 2 },
      { gateId: "BLOCH", qubit: 1, step: 0 },
    ],
    story: [
      "Alice chooses a random bit and basis to encode a photon.",
      "Bob measures in a randomly chosen basis and keeps only matching rounds.",
      "Public basis comparison reveals disturbances caused by Eve.",
    ],
  },
  {
    id: "e91",
    label: "E91",
    kind: "protocol",
    accent: "#ab47bc",
    summary: "Entanglement-based QKD where Bell correlations certify security.",
    support: "demo",
    nQubits: 2,
    gates: [
      { gateId: "H", qubit: 0, step: 0 },
      { gateId: "CNOT", qubit: 0, targetQubit: 1, step: 1 },
      { gateId: "Ry", qubit: 0, angle: tau / 8, step: 2 },
      { gateId: "Ry", qubit: 1, angle: -tau / 6, step: 2 },
      { gateId: "MEASURE", qubit: 0, step: 3 },
      { gateId: "MEASURE", qubit: 1, step: 3 },
    ],
    story: [
      "A source distributes entangled pairs to Alice and Bob.",
      "Measurement choices rotate local bases to test Bell inequality violation.",
      "Strong correlations indicate a secure shared channel.",
    ],
  },
  {
    id: "b92",
    label: "B92",
    kind: "protocol",
    accent: "#26a69a",
    summary: "Two non-orthogonal states give a leaner, lower-rate key distribution protocol.",
    support: "demo",
    nQubits: 1,
    initialStates: ["|+⟩"],
    gates: [
      { gateId: "Ry", qubit: 0, angle: Math.PI / 4, step: 0 },
      { gateId: "BLOCH", qubit: 0, step: 1 },
      { gateId: "MEASURE", qubit: 0, step: 2 },
    ],
    story: [
      "Alice sends one of two non-orthogonal states.",
      "Bob uses a measurement that sometimes yields an inconclusive result.",
      "Conclusive detections are kept to build the sifted key.",
    ],
  },
  {
    id: "teleport",
    label: "Teleportation",
    kind: "protocol",
    accent: "#8b5cf6",
    summary: "Move an unknown state onto Bob's qubit using entanglement plus two classical bits.",
    support: "implemented",
    nQubits: 3,
    initialStates: ["|+⟩", "|0⟩", "|0⟩"],
    gates: [
      { gateId: "H", qubit: 1, step: 0 },
      { gateId: "CNOT", qubit: 1, targetQubit: 2, step: 1 },
      { gateId: "CNOT", qubit: 0, targetQubit: 1, step: 2 },
      { gateId: "H", qubit: 0, step: 3 },
      { gateId: "MEASURE", qubit: 0, step: 4 },
      { gateId: "MEASURE", qubit: 1, step: 4 },
    ],
    story: [
      "Alice entangles Bob's qubit with an ancilla pair.",
      "A Bell-basis measurement converts the unknown state into classical correction bits.",
      "Bob reconstructs the state after receiving the bits.",
    ],
  },
  {
    id: "superdense",
    label: "Superdense Coding",
    kind: "protocol",
    accent: "#f59e0b",
    summary: "Pack two classical bits into one transmitted qubit by exploiting a shared Bell pair.",
    support: "implemented",
    nQubits: 2,
    gates: [
      { gateId: "H", qubit: 0, step: 0 },
      { gateId: "CNOT", qubit: 0, targetQubit: 1, step: 1 },
      { gateId: "Z", qubit: 0, step: 2 },
      { gateId: "X", qubit: 0, step: 3 },
      { gateId: "CNOT", qubit: 0, targetQubit: 1, step: 4 },
      { gateId: "H", qubit: 0, step: 5 },
      { gateId: "MEASURE", qubit: 0, step: 6 },
      { gateId: "MEASURE", qubit: 1, step: 6 },
    ],
    story: [
      "Alice and Bob pre-share an entangled pair.",
      "Alice applies one of four encodings corresponding to two classical bits.",
      "Bob decodes both bits after a joint measurement.",
    ],
  },
  {
    id: "qec",
    label: "Bit-Flip QEC",
    kind: "protocol",
    accent: "#ff6f00",
    summary: "A compact error-correction demonstration using redundancy and syndrome extraction.",
    support: "demo",
    nQubits: 3,
    gates: [
      { gateId: "CNOT", qubit: 0, targetQubit: 1, step: 0 },
      { gateId: "CNOT", qubit: 0, targetQubit: 2, step: 1 },
      { gateId: "X", qubit: 1, step: 2 },
      { gateId: "CNOT", qubit: 0, targetQubit: 1, step: 3 },
      { gateId: "CNOT", qubit: 0, targetQubit: 2, step: 4 },
      { gateId: "MEASURE", qubit: 1, step: 5 },
      { gateId: "MEASURE", qubit: 2, step: 5 },
    ],
    story: [
      "A logical qubit is encoded across multiple physical qubits.",
      "Syndrome checks reveal which line experienced a bit flip.",
      "A correction restores the logical information without learning the state itself.",
    ],
  },
  {
    id: "grover",
    label: "Grover",
    kind: "algorithm",
    accent: "#06b6d4",
    summary: "Iteratively amplify a marked state's amplitude for a quadratic search speedup.",
    support: "implemented",
    nQubits: 3,
    gates: [
      { gateId: "H", qubit: 0, step: 0 },
      { gateId: "H", qubit: 1, step: 0 },
      { gateId: "H", qubit: 2, step: 0 },
      { gateId: "CZ", qubit: 1, targetQubit: 2, step: 1 },
      { gateId: "Z", qubit: 0, step: 1 },
      { gateId: "H", qubit: 0, step: 2 },
      { gateId: "H", qubit: 1, step: 2 },
      { gateId: "H", qubit: 2, step: 2 },
      { gateId: "X", qubit: 0, step: 3 },
      { gateId: "X", qubit: 1, step: 3 },
      { gateId: "X", qubit: 2, step: 3 },
      { gateId: "TOFFOLI", qubit: 0, targetQubit: 2, controlQubit: 1, step: 4 },
      { gateId: "X", qubit: 0, step: 5 },
      { gateId: "X", qubit: 1, step: 5 },
      { gateId: "X", qubit: 2, step: 5 },
      { gateId: "H", qubit: 0, step: 6 },
      { gateId: "H", qubit: 1, step: 6 },
      { gateId: "H", qubit: 2, step: 6 },
    ],
    story: [
      "Hadamards spread amplitude uniformly over the search space.",
      "The oracle flips the phase of the marked basis state.",
      "Diffusion reflects amplitudes about the mean, boosting the target.",
    ],
  },
  {
    id: "shor",
    label: "Shor",
    kind: "algorithm",
    accent: "#ef4444",
    summary: "A compact period-finding style scene for factoring, with an honest demo label in the simulator.",
    support: "demo",
    nQubits: 4,
    gates: [
      { gateId: "H", qubit: 0, step: 0 },
      { gateId: "H", qubit: 1, step: 0 },
      { gateId: "H", qubit: 2, step: 0 },
      { gateId: "CNOT", qubit: 0, targetQubit: 3, step: 1 },
      { gateId: "CNOT", qubit: 1, targetQubit: 3, step: 2 },
      { gateId: "Rz", qubit: 0, angle: Math.PI / 2, step: 3 },
      { gateId: "Rz", qubit: 1, angle: Math.PI / 4, step: 3 },
      { gateId: "SWAP", qubit: 0, targetQubit: 2, step: 4 },
    ],
    story: [
      "Superposition explores many exponents in parallel.",
      "Periodicity is written into phases by modular arithmetic.",
      "An inverse Fourier transform reveals information about the hidden period.",
    ],
  },
  {
    id: "qft",
    label: "QFT",
    kind: "algorithm",
    accent: "#7c3aed",
    summary: "Rotate into the frequency domain with structured phases and qubit swaps.",
    support: "demo",
    nQubits: 3,
    gates: [
      { gateId: "H", qubit: 0, step: 0 },
      { gateId: "S", qubit: 1, step: 1 },
      { gateId: "T", qubit: 2, step: 1 },
      { gateId: "H", qubit: 1, step: 2 },
      { gateId: "S", qubit: 2, step: 3 },
      { gateId: "H", qubit: 2, step: 4 },
      { gateId: "SWAP", qubit: 0, targetQubit: 2, step: 5 },
    ],
    story: [
      "Each qubit accumulates phase information from lower-significance lines.",
      "Hadamards convert phase gradients into measurable amplitudes.",
      "A final bit reversal restores the natural order.",
    ],
  },
  {
    id: "qaoa",
    label: "QAOA",
    kind: "algorithm",
    accent: "#f97316",
    summary: "Alternate cost and mixer layers to steer a variational search over candidate solutions.",
    support: "stub",
    nQubits: 3,
    gates: [
      { gateId: "H", qubit: 0, step: 0 },
      { gateId: "H", qubit: 1, step: 0 },
      { gateId: "H", qubit: 2, step: 0 },
      { gateId: "CZ", qubit: 0, targetQubit: 1, step: 1 },
      { gateId: "CZ", qubit: 1, targetQubit: 2, step: 2 },
      { gateId: "Rx", qubit: 0, angle: Math.PI / 3, step: 3 },
      { gateId: "Rx", qubit: 1, angle: Math.PI / 3, step: 3 },
      { gateId: "Rx", qubit: 2, angle: Math.PI / 3, step: 3 },
    ],
    story: [
      "Start from a uniform superposition over candidate cuts.",
      "The cost Hamiltonian imprints problem structure as phase.",
      "Mixer rotations redistribute amplitude toward high-quality solutions.",
    ],
  },
  {
    id: "dj",
    label: "Deutsch-Jozsa",
    kind: "algorithm",
    accent: "#14b8a6",
    summary: "Distinguish balanced from constant oracles in a single coherent query.",
    support: "demo",
    nQubits: 3,
    initialStates: ["|0⟩", "|0⟩", "|1⟩"],
    gates: [
      { gateId: "H", qubit: 0, step: 0 },
      { gateId: "H", qubit: 1, step: 0 },
      { gateId: "H", qubit: 2, step: 0 },
      { gateId: "CNOT", qubit: 0, targetQubit: 2, step: 1 },
      { gateId: "CNOT", qubit: 1, targetQubit: 2, step: 2 },
      { gateId: "H", qubit: 0, step: 3 },
      { gateId: "H", qubit: 1, step: 3 },
      { gateId: "MEASURE", qubit: 0, step: 4 },
      { gateId: "MEASURE", qubit: 1, step: 4 },
    ],
    story: [
      "Query qubits and an ancilla are placed into interference-ready states.",
      "A balanced oracle writes different phases than a constant oracle.",
      "The final Hadamards make the distinction visible in one shot.",
    ],
  },
  {
    id: "bv",
    label: "Bernstein-Vazirani",
    kind: "algorithm",
    accent: "#6366f1",
    summary: "Recover a hidden bit string with one oracle query.",
    support: "demo",
    nQubits: 4,
    initialStates: ["|0⟩", "|0⟩", "|0⟩", "|1⟩"],
    gates: [
      { gateId: "H", qubit: 0, step: 0 },
      { gateId: "H", qubit: 1, step: 0 },
      { gateId: "H", qubit: 2, step: 0 },
      { gateId: "H", qubit: 3, step: 0 },
      { gateId: "CNOT", qubit: 0, targetQubit: 3, step: 1 },
      { gateId: "CNOT", qubit: 2, targetQubit: 3, step: 2 },
      { gateId: "H", qubit: 0, step: 3 },
      { gateId: "H", qubit: 1, step: 3 },
      { gateId: "H", qubit: 2, step: 3 },
      { gateId: "MEASURE", qubit: 0, step: 4 },
      { gateId: "MEASURE", qubit: 1, step: 4 },
      { gateId: "MEASURE", qubit: 2, step: 4 },
    ],
    story: [
      "Phase kickback encodes the secret string into the query register.",
      "Interference collapses the unknown oracle into a deterministic answer.",
      "One measurement reveals the full hidden string.",
    ],
  },
  {
    id: "simon",
    label: "Simon's Algorithm",
    kind: "algorithm",
    accent: "#ea580c",
    summary: "Use interference to uncover a hidden xor period exponentially faster than classical search.",
    support: "demo",
    nQubits: 4,
    gates: [
      { gateId: "H", qubit: 0, step: 0 },
      { gateId: "H", qubit: 1, step: 0 },
      { gateId: "CNOT", qubit: 0, targetQubit: 2, step: 1 },
      { gateId: "CNOT", qubit: 1, targetQubit: 3, step: 1 },
      { gateId: "H", qubit: 0, step: 2 },
      { gateId: "H", qubit: 1, step: 2 },
      { gateId: "MEASURE", qubit: 0, step: 3 },
      { gateId: "MEASURE", qubit: 1, step: 3 },
    ],
    story: [
      "The oracle maps paired inputs to the same output based on a hidden xor mask.",
      "Measuring the output register leaves the input in a correlated superposition.",
      "Repeated interference samples linear constraints that reveal the secret string.",
    ],
  },
  {
    id: "qpe",
    label: "Phase Estimation",
    kind: "algorithm",
    accent: "#a855f7",
    summary: "Encode an eigenphase into a readout register and decode it via inverse QFT.",
    support: "demo",
    nQubits: 3,
    initialStates: ["|0⟩", "|0⟩", "|1⟩"],
    gates: [
      { gateId: "H", qubit: 0, step: 0 },
      { gateId: "H", qubit: 1, step: 0 },
      { gateId: "CZ", qubit: 0, targetQubit: 2, step: 1 },
      { gateId: "Rz", qubit: 1, angle: Math.PI / 2, step: 2 },
      { gateId: "H", qubit: 1, step: 3 },
      { gateId: "SWAP", qubit: 0, targetQubit: 1, step: 4 },
      { gateId: "MEASURE", qubit: 0, step: 5 },
      { gateId: "MEASURE", qubit: 1, step: 5 },
    ],
    story: [
      "Control qubits accumulate powers of the unknown eigenphase.",
      "Inverse Fourier structure converts relative phase into binary digits.",
      "The readout register yields an estimate of the phase.",
    ],
  },
  {
    id: "vqe",
    label: "VQE",
    kind: "algorithm",
    accent: "#ec4899",
    summary: "A variational ansatz optimized classically to minimize measured energy.",
    support: "demo",
    nQubits: 2,
    gates: [
      { gateId: "Ry", qubit: 0, angle: Math.PI / 3, step: 0 },
      { gateId: "Ry", qubit: 1, angle: Math.PI / 4, step: 0 },
      { gateId: "CNOT", qubit: 0, targetQubit: 1, step: 1 },
      { gateId: "Rz", qubit: 1, angle: Math.PI / 5, step: 2 },
      { gateId: "MEASURE", qubit: 0, step: 3 },
      { gateId: "MEASURE", qubit: 1, step: 3 },
    ],
    story: [
      "A parameterized ansatz prepares a trial wavefunction.",
      "Measurements estimate the Hamiltonian expectation value.",
      "A classical optimizer updates parameters to descend the energy landscape.",
    ],
  },
  {
    id: "qwalk",
    label: "Quantum Walk",
    kind: "algorithm",
    accent: "#0f766e",
    summary: "A coin and shift spread amplitude ballistically across positions.",
    support: "demo",
    nQubits: 3,
    gates: [
      { gateId: "H", qubit: 0, step: 0 },
      { gateId: "CNOT", qubit: 0, targetQubit: 1, step: 1 },
      { gateId: "SWAP", qubit: 1, targetQubit: 2, step: 2 },
      { gateId: "H", qubit: 0, step: 3 },
      { gateId: "CNOT", qubit: 0, targetQubit: 1, step: 4 },
      { gateId: "SWAP", qubit: 1, targetQubit: 2, step: 5 },
    ],
    story: [
      "A coin qubit determines left-versus-right propagation.",
      "Conditional shifts entangle direction with position.",
      "Interference produces the wide, sharp-edged quantum walk profile.",
    ],
  },
]

export function getLearningExperience(id: string | null | undefined) {
  return LEARNING_EXPERIENCES.find((item) => item.id === id) ?? LEARNING_EXPERIENCES[0]
}
