from __future__ import annotations

from api.schemas.workspace import (
    WorkspaceBenchmarkProfile,
    WorkspaceCatalogResponse,
    WorkspaceSyntaxItem,
    WorkspaceTemplate,
    WorkspaceTemplateParameter,
)


SYNTAX_REFERENCE = [
    WorkspaceSyntaxItem(
        syntax="INIT q0",
        description="Initialize a qubit in the |0> state.",
        category="quantum",
        example="INIT q0",
    ),
    WorkspaceSyntaxItem(
        syntax="INIT q1 1",
        description="Initialize a qubit in the |1> state.",
        category="quantum",
        example="INIT q1 1",
    ),
    WorkspaceSyntaxItem(
        syntax="INIT q2 +",
        description="Initialize a qubit in the |+> state and mark it as a superposition state.",
        category="quantum",
        example="INIT q2 +",
    ),
    WorkspaceSyntaxItem(
        syntax="RESET q0",
        description="Clear a qubit back to |0> and remove entanglement links.",
        category="quantum",
        example="RESET q0",
    ),
    WorkspaceSyntaxItem(
        syntax="H q0",
        description="Toggle a qubit between the Z basis and the X basis using the simplified Hadamard rule.",
        category="quantum",
        example="H q0",
    ),
    WorkspaceSyntaxItem(
        syntax="X q0",
        description="Flip a qubit in the computational basis.",
        category="quantum",
        example="X q0",
    ),
    WorkspaceSyntaxItem(
        syntax="Y q0",
        description="Apply a simplified Y rotation using X plus phase behavior.",
        category="quantum",
        example="Y q0",
    ),
    WorkspaceSyntaxItem(
        syntax="Z q0",
        description="Flip the X-basis phase marker between |+> and |->.",
        category="quantum",
        example="Z q0",
    ),
    WorkspaceSyntaxItem(
        syntax="S q0",
        description="Apply a simplified quarter-phase update to a qubit.",
        category="quantum",
        example="S q0",
    ),
    WorkspaceSyntaxItem(
        syntax="T q0",
        description="Apply a simplified eighth-turn phase update to a qubit.",
        category="quantum",
        example="T q0",
    ),
    WorkspaceSyntaxItem(
        syntax="SDG q0",
        description="Apply the inverse simplified S phase rule.",
        category="quantum",
        example="SDG q0",
    ),
    WorkspaceSyntaxItem(
        syntax="TDG q0",
        description="Apply the inverse simplified T phase rule.",
        category="quantum",
        example="TDG q0",
    ),
    WorkspaceSyntaxItem(
        syntax="SX q0",
        description="Apply a simplified square-root-X style superposition update.",
        category="quantum",
        example="SX q0",
    ),
    WorkspaceSyntaxItem(
        syntax="RX q0 1.5708",
        description="Apply a simplified X-axis rotation with a numeric angle in radians.",
        category="quantum",
        example="RX q0 1.5708",
    ),
    WorkspaceSyntaxItem(
        syntax="RY q0 1.5708",
        description="Apply a simplified Y-axis rotation with a numeric angle in radians.",
        category="quantum",
        example="RY q0 1.5708",
    ),
    WorkspaceSyntaxItem(
        syntax="RZ q0 1.5708",
        description="Apply a simplified Z-axis rotation with a numeric angle in radians.",
        category="quantum",
        example="RZ q0 1.5708",
    ),
    WorkspaceSyntaxItem(
        syntax="CNOT q0 q1",
        description="Flip the target when the control is |1>, or create a basic entanglement link when a superposition is involved.",
        category="quantum",
        example="CNOT q0 q1",
    ),
    WorkspaceSyntaxItem(
        syntax="SWAP q0 q1",
        description="Swap the simplified runtime states of two qubits.",
        category="quantum",
        example="SWAP q0 q1",
    ),
    WorkspaceSyntaxItem(
        syntax="CZ q0 q1",
        description="Apply a simplified controlled phase update or correlation link.",
        category="quantum",
        example="CZ q0 q1",
    ),
    WorkspaceSyntaxItem(
        syntax="TOFFOLI q0 q1 q2",
        description="Apply a simplified doubly-controlled X gate using two controls and one target.",
        category="quantum",
        example="TOFFOLI q0 q1 q2",
    ),
    WorkspaceSyntaxItem(
        syntax="MEASURE q0 [BASIS X]",
        description="Measure a qubit in the X basis. The bracket form and the plain BASIS form are both accepted.",
        category="quantum",
        example="MEASURE q0 BASIS X",
    ),
    WorkspaceSyntaxItem(
        syntax="MEASURE q0 [BASIS Z]",
        description="Measure a qubit in the Z basis. If omitted, Z is used by default.",
        category="quantum",
        example="MEASURE q0",
    ),
    WorkspaceSyntaxItem(
        syntax="ACTOR Alice",
        description="Register an actor lane for ownership and transport events.",
        category="actor",
        example="ACTOR Alice",
    ),
    WorkspaceSyntaxItem(
        syntax="ASSIGN q0 Alice",
        description="Assign a qubit to an actor.",
        category="actor",
        example="ASSIGN q0 Alice",
    ),
    WorkspaceSyntaxItem(
        syntax="SEND q0 Alice Bob",
        description="Move a qubit from one actor to another and record a transport event.",
        category="transport",
        example="SEND q0 Alice Bob",
    ),
    WorkspaceSyntaxItem(
        syntax="INTERCEPT q0 Eve",
        description="Intercept a qubit with a third actor. In the simplified engine this performs a hidden Z-basis disturbance when needed.",
        category="transport",
        example="INTERCEPT q0 Eve",
    ),
    WorkspaceSyntaxItem(
        syntax="LABEL BellPair",
        description="Add a timeline marker without changing state.",
        category="annotation",
        example="LABEL BellPair",
    ),
    WorkspaceSyntaxItem(
        syntax="NOTE share entanglement before sending",
        description="Store an inline note in the execution trace.",
        category="annotation",
        example="NOTE Bob receives the second qubit here",
    ),
    WorkspaceSyntaxItem(
        syntax="WAIT 1",
        description="Insert a visual spacer step.",
        category="annotation",
        example="WAIT 1",
    ),
    WorkspaceSyntaxItem(
        syntax="BARRIER",
        description="Insert a barrier marker in the circuit timeline.",
        category="annotation",
        example="BARRIER",
    ),
    WorkspaceSyntaxItem(
        syntax="SUPERPOSE q0",
        description="Macro form that expands to a Hadamard gate.",
        category="macro",
        example="SUPERPOSE q0",
        expands_to=["H q0"],
    ),
    WorkspaceSyntaxItem(
        syntax="BELL q0 q1",
        description="Macro form that prepares a Bell-pair-style entanglement pattern.",
        category="macro",
        example="BELL q0 q1",
        expands_to=["INIT q0", "INIT q1", "H q0", "CNOT q0 q1"],
    ),
]


TEMPLATES = [
    # ── Category 1: FOUNDATIONAL ALGORITHMS ──────────────────────────────────
    WorkspaceTemplate(
        id="deutsch",
        title="Deutsch Algorithm",
        kind="algorithm",
        description="Decides if a 1-bit function f is constant or balanced with a single query.",
        tags=["deutsch", "foundational", "oracle", "difficulty:beginner"],
        code="\n".join([
            "NOTE Deutsch Algorithm — constant vs balanced oracle",
            "",
            "INIT q0 1",
            "INIT q1 +",
            "",
            "LABEL Apply Hadamard to both qubits",
            "H q0",
            "H q1",
            "",
            "LABEL Oracle: balanced f(x) = x (CNOT encodes it)",
            "CNOT q0 q1",
            "",
            "LABEL Final Hadamard on query qubit",
            "H q0",
            "",
            "LABEL Readout — |0⟩ constant, |1⟩ balanced",
            "MEASURE q0 BASIS Z",
        ]),
    ),
    WorkspaceTemplate(
        id="deutsch_jozsa",
        title="Deutsch-Jozsa Algorithm",
        kind="algorithm",
        description="Generalises Deutsch's algorithm to n-bit functions, deciding constant vs balanced in one query.",
        tags=["deutsch-jozsa", "foundational", "oracle", "difficulty:beginner"],
        code="\n".join([
            "NOTE Deutsch-Jozsa — 3-bit balanced oracle (XOR parity)",
            "",
            "INIT q0",
            "INIT q1",
            "INIT q2",
            "INIT q3 1",
            "",
            "LABEL Superpose input qubits, prepare ancilla in |-⟩",
            "H q0",
            "H q1",
            "H q2",
            "H q3",
            "",
            "LABEL Oracle: balanced (XOR of all inputs)",
            "CNOT q0 q3",
            "CNOT q1 q3",
            "CNOT q2 q3",
            "",
            "LABEL Final Hadamards on input qubits",
            "H q0",
            "H q1",
            "H q2",
            "",
            "LABEL Readout — all |0⟩ means constant",
            "MEASURE q0 BASIS Z",
            "MEASURE q1 BASIS Z",
            "MEASURE q2 BASIS Z",
        ]),
    ),
    WorkspaceTemplate(
        id="bernstein_vazirani",
        title="Bernstein-Vazirani Algorithm",
        kind="algorithm",
        description="Recovers a hidden bit-string s from f(x)=s·x with a single quantum query.",
        tags=["bernstein-vazirani", "foundational", "oracle", "difficulty:beginner"],
        parameters=[
            WorkspaceTemplateParameter(
                name="hidden_string",
                label="Hidden Bit String",
                type="string",
                default="110",
            )
        ],
        code="\n".join([
            "NOTE Bernstein-Vazirani — hidden string s={{hidden_string}}",
            "",
            "INIT q0",
            "INIT q1",
            "INIT q2",
            "INIT q3 1",
            "",
            "H q0",
            "H q1",
            "H q2",
            "H q3",
            "",
            "LABEL Oracle encodes s={{hidden_string}}",
            "{{oracle_gates}}",
            "",
            "H q0",
            "H q1",
            "H q2",
            "",
            "LABEL Readout reveals hidden string",
            "MEASURE q0 BASIS Z",
            "MEASURE q1 BASIS Z",
            "MEASURE q2 BASIS Z",
        ]),
    ),
    WorkspaceTemplate(
        id="simon",
        title="Simon's Algorithm",
        kind="algorithm",
        description="Finds the hidden period s of a 2-to-1 function f(x)=f(x⊕s) exponentially faster than classically.",
        tags=["simon", "foundational", "period-finding", "difficulty:intermediate"],
        code="\n".join([
            "NOTE Simon's Algorithm — hidden period s=11 (2-qubit example)",
            "",
            "INIT q0",
            "INIT q1",
            "INIT q2",
            "INIT q3",
            "",
            "LABEL Superpose input register",
            "H q0",
            "H q1",
            "",
            "LABEL Oracle for s=11: copies input XOR s into output register",
            "CNOT q0 q2",
            "CNOT q1 q3",
            "CNOT q0 q3",
            "CNOT q1 q2",
            "",
            "LABEL Measure output (collapses to one coset)",
            "MEASURE q2 BASIS Z",
            "MEASURE q3 BASIS Z",
            "",
            "LABEL Hadamard input register",
            "H q0",
            "H q1",
            "",
            "LABEL Readout — classical post-processing finds s",
            "MEASURE q0 BASIS Z",
            "MEASURE q1 BASIS Z",
        ]),
    ),

    # ── Category 2: COMMUNICATION & SECURITY ────────────────────────────────
    WorkspaceTemplate(
        id="bell_pair",
        title="Bell Pair Starter",
        kind="circuit",
        description="Create a Bell pair and inspect the circuit, Bloch vectors, and measurement history.",
        tags=["entanglement", "starter"],
        code="\n".join([
            "LABEL Bell Pair",
            "INIT q0",
            "INIT q1",
            "H q0",
            "CNOT q0 q1",
            "MEASURE q0 BASIS Z",
            "MEASURE q1 BASIS Z",
        ]),
    ),
    WorkspaceTemplate(
        id="bb84_eavesdrop",
        title="BB84 With Eve",
        kind="protocol",
        description="Model preparation, sending, interception, and measurement with actors.",
        tags=["bb84", "qkd", "actors"],
        code="\n".join([
            "ACTOR Alice",
            "ACTOR Bob",
            "ACTOR Eve",
            "LABEL Prepare photon",
            "INIT q0 +",
            "ASSIGN q0 Alice",
            "SEND q0 Alice Bob",
            "INTERCEPT q0 Eve",
            "SEND q0 Eve Bob",
            "MEASURE q0 BASIS Z",
        ]),
    ),
    WorkspaceTemplate(
        id="teleportation_simplified",
        title="Teleportation Walkthrough",
        kind="protocol",
        description="A simplified teleportation-style flow driven entirely by pseudocode.",
        tags=["teleportation", "entanglement"],
        code="\n".join([
            "ACTOR Alice",
            "ACTOR Bob",
            "INIT q0 +",
            "INIT q1",
            "INIT q2",
            "ASSIGN q0 Alice",
            "ASSIGN q1 Alice",
            "ASSIGN q2 Bob",
            "LABEL Share entanglement",
            "H q1",
            "CNOT q1 q2",
            "LABEL Alice encodes the Bell measurement",
            "CNOT q0 q1",
            "H q0",
            "MEASURE q0 BASIS Z",
            "MEASURE q1 BASIS Z",
            "SEND q1 Alice Bob",
        ]),
    ),
    WorkspaceTemplate(
        id="superdense_simplified",
        title="Superdense Coding",
        kind="protocol",
        description="Prepare a Bell pair, encode with X and Z, and send one qubit.",
        tags=["superdense", "communication"],
        code="\n".join([
            "ACTOR Alice",
            "ACTOR Bob",
            "INIT q0",
            "INIT q1",
            "ASSIGN q0 Alice",
            "ASSIGN q1 Bob",
            "BELL q0 q1",
            "LABEL Encode message 11",
            "Z q0",
            "X q0",
            "SEND q0 Alice Bob",
            "MEASURE q0 BASIS Z",
            "MEASURE q1 BASIS Z",
        ]),
    ),
    WorkspaceTemplate(
        id="n_qubit_teleportation",
        title="N-Qubit Teleportation",
        kind="protocol",
        description="Teleports a 2-qubit state using two independent Bell channels.",
        tags=["teleportation", "multi-qubit", "communication", "difficulty:intermediate"],
        code="\n".join([
            "NOTE N-Qubit Teleportation (2-qubit payload example)",
            "",
            "ACTOR Alice",
            "ACTOR Bob",
            "",
            "LABEL Payload qubits to teleport",
            "INIT q0 +",
            "INIT q1 +",
            "",
            "LABEL Bell channel 1 for q0",
            "INIT q2",
            "INIT q3",
            "H q2",
            "CNOT q2 q3",
            "ASSIGN q2 Alice",
            "ASSIGN q3 Bob",
            "",
            "LABEL Bell channel 2 for q1",
            "INIT q4",
            "INIT q5",
            "H q4",
            "CNOT q4 q5",
            "ASSIGN q4 Alice",
            "ASSIGN q5 Bob",
            "",
            "LABEL Teleport q0",
            "CNOT q0 q2",
            "H q0",
            "MEASURE q0 BASIS Z",
            "MEASURE q2 BASIS Z",
            "SEND q2 Alice Bob",
            "",
            "LABEL Teleport q1",
            "CNOT q1 q4",
            "H q1",
            "MEASURE q1 BASIS Z",
            "MEASURE q4 BASIS Z",
            "SEND q4 Alice Bob",
        ]),
    ),
    WorkspaceTemplate(
        id="veto_algorithm",
        title="Veto Algorithm",
        kind="protocol",
        description="Quantum veto protocol: any participant can anonymously veto a decision using shared GHZ entanglement.",
        tags=["veto", "multiparty", "communication", "difficulty:intermediate"],
        code="\n".join([
            "NOTE Quantum Veto Protocol (3-party GHZ-based)",
            "",
            "ACTOR Alice",
            "ACTOR Bob",
            "ACTOR Charlie",
            "",
            "LABEL Prepare GHZ state",
            "INIT q0",
            "INIT q1",
            "INIT q2",
            "H q0",
            "CNOT q0 q1",
            "CNOT q0 q2",
            "",
            "ASSIGN q0 Alice",
            "ASSIGN q1 Bob",
            "ASSIGN q2 Charlie",
            "",
            "LABEL Each party measures — veto = X then measure",
            "NOTE Alice vetoes by flipping her qubit",
            "X q0",
            "MEASURE q0 BASIS X",
            "MEASURE q1 BASIS X",
            "MEASURE q2 BASIS X",
            "",
            "NOTE Parity of results reveals veto without identity",
        ]),
    ),
    WorkspaceTemplate(
        id="qpc_socialist_millionaire",
        title="QPC (Socialist Millionaire)",
        kind="protocol",
        description="Quantum Private Comparison: two parties check equality of secrets without revealing them.",
        tags=["qpc", "private-comparison", "security", "difficulty:advanced"],
        code="\n".join([
            "NOTE Quantum Private Comparison (Socialist Millionaire)",
            "NOTE Two parties check if s_Alice == s_Bob",
            "",
            "ACTOR Alice",
            "ACTOR Bob",
            "ACTOR TP",
            "",
            "LABEL TP prepares Bell pairs",
            "INIT q0",
            "INIT q1",
            "INIT q2",
            "INIT q3",
            "H q0",
            "CNOT q0 q1",
            "H q2",
            "CNOT q2 q3",
            "",
            "ASSIGN q0 Alice",
            "ASSIGN q1 Bob",
            "ASSIGN q2 Alice",
            "ASSIGN q3 Bob",
            "",
            "LABEL Alice encodes her secret bit (0=I, 1=X)",
            "NOTE If Alice's secret=1:",
            "X q0",
            "",
            "LABEL Bob encodes his secret bit",
            "NOTE If Bob's secret=1:",
            "X q1",
            "",
            "LABEL Both measure in Bell basis",
            "CNOT q0 q2",
            "H q0",
            "MEASURE q0 BASIS Z",
            "MEASURE q2 BASIS Z",
            "",
            "CNOT q1 q3",
            "H q1",
            "MEASURE q1 BASIS Z",
            "MEASURE q3 BASIS Z",
            "",
            "NOTE Matching results → secrets are equal",
        ]),
    ),

    # ── Category 3: SEARCH & MATH ────────────────────────────────────────────
    WorkspaceTemplate(
        id="grover_search",
        title="Grover's Search",
        kind="algorithm",
        description=(
            "Grover's search algorithm on 2 qubits — marks |11⟩ as the solution, "
            "then amplifies it with one oracle+diffusion iteration."
        ),
        tags=["grover", "search", "difficulty:beginner", "ref:pennylane"],
        code="\n".join([
            "NOTE Grover's search on 2 qubits — marks |11⟩",
            "NOTE Ref: PennyLane GroverOperator",
            "",
            "INIT q0",
            "INIT q1",
            "",
            "LABEL Uniform superposition",
            "H q0",
            "H q1",
            "",
            "LABEL Oracle — phase-flip |11⟩",
            "CZ q0 q1",
            "",
            "LABEL Diffusion operator (2|s⟩⟨s| − I)",
            "H q0",
            "H q1",
            "X q0",
            "X q1",
            "CZ q0 q1",
            "X q0",
            "X q1",
            "H q0",
            "H q1",
            "",
            "LABEL Readout",
            "MEASURE q0 BASIS Z",
            "MEASURE q1 BASIS Z",
        ]),
    ),
    WorkspaceTemplate(
        id="qft_3qubit",
        title="Quantum Fourier Transform",
        kind="algorithm",
        description=(
            "3-qubit QFT using the standard decomposition: Hadamard, "
            "controlled-rotation (via CNOT+RZ), and SWAP bit-reversal."
        ),
        tags=["qft", "transform", "difficulty:intermediate", "ref:pennylane"],
        code="\n".join([
            "NOTE 3-qubit Quantum Fourier Transform",
            "NOTE Ref: PennyLane QFT",
            "",
            "INIT q0 1",
            "INIT q1",
            "INIT q2",
            "",
            "LABEL QFT — qubit 0",
            "H q0",
            "CNOT q1 q0",
            "RZ q0 -1.5708",
            "CNOT q1 q0",
            "RZ q0 1.5708",
            "CNOT q2 q0",
            "RZ q0 -0.7854",
            "CNOT q2 q0",
            "RZ q0 0.7854",
            "",
            "LABEL QFT — qubit 1",
            "H q1",
            "CNOT q2 q1",
            "RZ q1 -1.5708",
            "CNOT q2 q1",
            "RZ q1 1.5708",
            "",
            "LABEL QFT — qubit 2",
            "H q2",
            "",
            "LABEL Bit-reversal SWAP",
            "SWAP q0 q2",
            "",
            "LABEL Readout",
            "MEASURE q0 BASIS Z",
            "MEASURE q1 BASIS Z",
            "MEASURE q2 BASIS Z",
        ]),
    ),
    WorkspaceTemplate(
        id="qpe_simple",
        title="Quantum Phase Estimation",
        kind="algorithm",
        description=(
            "Phase estimation with 1 target qubit and 2 estimation qubits. "
            "Estimates the phase of a T gate (θ=π/4)."
        ),
        tags=["qpe", "phase-estimation", "difficulty:advanced", "ref:pennylane"],
        code="\n".join([
            "NOTE Quantum Phase Estimation",
            "NOTE Target: T gate (phase θ = π/4)",
            "NOTE Estimation qubits: q0 (MSB), q1 (LSB)",
            "NOTE Target qubit: q2",
            "",
            "INIT q0",
            "INIT q1",
            "INIT q2",
            "",
            "LABEL Prepare eigenstate |1⟩ on target",
            "X q2",
            "",
            "LABEL Hadamard estimation qubits",
            "H q0",
            "H q1",
            "",
            "LABEL Controlled-U¹ (T gate)",
            "CNOT q1 q2",
            "RZ q2 -0.7854",
            "CNOT q1 q2",
            "RZ q2 0.7854",
            "",
            "LABEL Controlled-U² (S gate)",
            "CNOT q0 q2",
            "RZ q2 -1.5708",
            "CNOT q0 q2",
            "RZ q2 1.5708",
            "",
            "LABEL Inverse QFT on estimation qubits",
            "SWAP q0 q1",
            "H q0",
            "CNOT q1 q0",
            "RZ q0 0.7854",
            "CNOT q1 q0",
            "RZ q0 -0.7854",
            "H q1",
            "",
            "LABEL Readout",
            "MEASURE q0 BASIS Z",
            "MEASURE q1 BASIS Z",
        ]),
    ),
    WorkspaceTemplate(
        id="shor_factorization",
        title="Shor's Algorithm – Factorization",
        kind="algorithm",
        description="Simplified Shor's: period-finding circuit for N=15, a=7 using 4 counting qubits.",
        tags=["shor", "factorization", "period-finding", "difficulty:advanced"],
        code="\n".join([
            "NOTE Shor's Algorithm — factoring N=15 with a=7",
            "NOTE Period r=4 → factors 3 and 5",
            "",
            "INIT q0",
            "INIT q1",
            "INIT q2",
            "INIT q3",
            "INIT q4",
            "",
            "LABEL Superpose counting register",
            "H q0",
            "H q1",
            "H q2",
            "H q3",
            "",
            "LABEL Prepare target register |1⟩",
            "X q4",
            "",
            "LABEL Modular exponentiation oracle (simplified)",
            "NOTE 7^1 mod 15 = 7 — encoded as controlled-X",
            "CNOT q3 q4",
            "NOTE 7^2 mod 15 = 4 — encoded as controlled-phase",
            "CZ q2 q4",
            "NOTE 7^4 mod 15 = 1 — identity",
            "",
            "LABEL Inverse QFT on counting register",
            "SWAP q0 q3",
            "H q0",
            "CNOT q1 q0",
            "RZ q0 0.7854",
            "CNOT q1 q0",
            "H q1",
            "H q2",
            "H q3",
            "",
            "LABEL Readout — period encoded in binary",
            "MEASURE q0 BASIS Z",
            "MEASURE q1 BASIS Z",
            "MEASURE q2 BASIS Z",
            "MEASURE q3 BASIS Z",
        ]),
    ),
    WorkspaceTemplate(
        id="hhl_algorithm",
        title="HHL Algorithm",
        kind="algorithm",
        description="Harrow-Hassidim-Lloyd: quantum linear systems solver. Simplified 2-qubit demonstration.",
        tags=["hhl", "linear-systems", "difficulty:advanced"],
        code="\n".join([
            "NOTE HHL Algorithm — simplified 2x2 linear system Ax=b",
            "NOTE Solves A|x⟩ = |b⟩ where A has eigenvalues 1 and 3",
            "",
            "INIT q0",
            "INIT q1",
            "INIT q2",
            "",
            "LABEL Encode |b⟩ in the input register",
            "H q2",
            "",
            "LABEL QPE: estimate eigenvalues of A",
            "H q0",
            "H q1",
            "CNOT q0 q2",
            "RZ q2 1.5708",
            "CNOT q0 q2",
            "CNOT q1 q2",
            "RZ q2 0.7854",
            "CNOT q1 q2",
            "",
            "LABEL Ancilla rotation (controlled 1/λ rotation)",
            "NOTE Simplified: encode reciprocal via RY on ancilla",
            "RY q0 1.0472",
            "RY q1 0.5236",
            "",
            "LABEL Uncompute QPE",
            "H q0",
            "H q1",
            "",
            "LABEL Readout",
            "MEASURE q0 BASIS Z",
            "MEASURE q1 BASIS Z",
            "MEASURE q2 BASIS Z",
        ]),
    ),

    # ── Category 4: QML ──────────────────────────────────────────────────────
    WorkspaceTemplate(
        id="qsvm",
        title="QSVM Algorithm",
        kind="algorithm",
        description="Quantum Support Vector Machine: encodes two data points and computes kernel overlap.",
        tags=["qsvm", "qml", "classification", "difficulty:intermediate"],
        code="\n".join([
            "NOTE Quantum SVM — kernel circuit for 2 features",
            "",
            "INIT q0",
            "INIT q1",
            "",
            "LABEL Encode data point x1 = (π/4, π/3)",
            "RY q0 0.7854",
            "RY q1 1.0472",
            "",
            "LABEL Entangle features (ZZ feature map)",
            "CNOT q0 q1",
            "RZ q1 1.5708",
            "CNOT q0 q1",
            "",
            "LABEL Encode data point x2 for kernel comparison",
            "RY q0 0.5236",
            "RY q1 0.7854",
            "",
            "LABEL Measure kernel value",
            "MEASURE q0 BASIS Z",
            "MEASURE q1 BASIS Z",
        ]),
    ),
    WorkspaceTemplate(
        id="qkmean",
        title="QKmean Algorithm",
        kind="algorithm",
        description="Quantum K-Means: uses swap test to compute distances between quantum-encoded data points.",
        tags=["qkmean", "qml", "clustering", "difficulty:intermediate"],
        code="\n".join([
            "NOTE Quantum K-Means — swap test for cluster assignment",
            "",
            "INIT q0",
            "INIT q1",
            "INIT q2",
            "",
            "LABEL Ancilla for swap test",
            "H q0",
            "",
            "LABEL Encode data point",
            "RY q1 1.0472",
            "",
            "LABEL Encode centroid",
            "RY q2 0.5236",
            "",
            "LABEL Controlled-SWAP (Fredkin) for overlap",
            "CNOT q1 q2",
            "CNOT q0 q1",
            "CNOT q1 q2",
            "",
            "LABEL Final Hadamard on ancilla",
            "H q0",
            "",
            "LABEL Measure ancilla — |0⟩ probability ~ cos²(θ/2)",
            "MEASURE q0 BASIS Z",
        ]),
    ),
    WorkspaceTemplate(
        id="qknn",
        title="QKNN Algorithm",
        kind="algorithm",
        description="Quantum K-Nearest Neighbours: amplitude encoding + Hadamard test for similarity.",
        tags=["qknn", "qml", "classification", "difficulty:intermediate"],
        code="\n".join([
            "NOTE Quantum KNN — Hadamard test for inner product",
            "",
            "INIT q0",
            "INIT q1",
            "INIT q2",
            "",
            "LABEL Prepare ancilla",
            "H q0",
            "",
            "LABEL Encode test point",
            "RY q1 0.7854",
            "",
            "LABEL Encode training point",
            "RY q2 1.2566",
            "",
            "LABEL Controlled-U: apply training point unitary",
            "CNOT q0 q2",
            "RY q2 0.3927",
            "CNOT q0 q2",
            "",
            "LABEL Hadamard test",
            "H q0",
            "MEASURE q0 BASIS Z",
            "",
            "NOTE P(0) ≈ (1 + Re⟨test|train⟩)/2",
        ]),
    ),
    WorkspaceTemplate(
        id="qhc",
        title="QHC Algorithm",
        kind="algorithm",
        description="Quantum Hierarchical Clustering: computes pairwise similarity using amplitude encoding.",
        tags=["qhc", "qml", "clustering", "difficulty:intermediate"],
        code="\n".join([
            "NOTE Quantum Hierarchical Clustering — pairwise similarity",
            "",
            "INIT q0",
            "INIT q1",
            "INIT q2",
            "",
            "LABEL Encode data points for two clusters",
            "RY q0 0.9553",
            "RY q1 0.6435",
            "RY q2 0.3217",
            "",
            "LABEL Compute overlap via pairwise entanglement",
            "H q0",
            "CNOT q0 q1",
            "CNOT q0 q2",
            "",
            "LABEL Measure to collapse cluster assignments",
            "MEASURE q0 BASIS Z",
            "MEASURE q1 BASIS Z",
            "MEASURE q2 BASIS Z",
        ]),
    ),
    WorkspaceTemplate(
        id="qpca",
        title="QPCA Algorithm",
        kind="algorithm",
        description="Quantum PCA: uses quantum phase estimation on the density matrix to extract principal components.",
        tags=["qpca", "qml", "dimensionality-reduction", "difficulty:advanced"],
        code="\n".join([
            "NOTE Quantum PCA — extract principal component via QPE",
            "",
            "INIT q0",
            "INIT q1",
            "INIT q2",
            "",
            "LABEL Prepare density matrix eigenstate (|+⟩)",
            "H q1",
            "",
            "LABEL QPE estimation qubits",
            "H q0",
            "H q2",
            "",
            "LABEL Controlled unitary (density matrix evolution)",
            "CNOT q0 q1",
            "RZ q1 1.5708",
            "CNOT q0 q1",
            "",
            "LABEL Uncompute — extract phase into ancilla",
            "H q0",
            "H q2",
            "",
            "LABEL Readout — phase encodes principal eigenvalue",
            "MEASURE q0 BASIS Z",
            "MEASURE q2 BASIS Z",
        ]),
    ),
    WorkspaceTemplate(
        id="qperceptron",
        title="QPerceptron Algorithm",
        kind="algorithm",
        description="Quantum Perceptron: single-layer trainable unitary with threshold activation via measurement.",
        tags=["qperceptron", "qml", "classification", "difficulty:beginner"],
        code="\n".join([
            "NOTE Quantum Perceptron — trainable single-qubit neuron",
            "",
            "INIT q0",
            "",
            "LABEL Encode input feature x",
            "RY q0 1.0472",
            "",
            "LABEL Apply trained weight w",
            "RZ q0 0.5236",
            "",
            "LABEL Activation: Hadamard + threshold measurement",
            "H q0",
            "MEASURE q0 BASIS Z",
            "",
            "NOTE |0⟩ → NOT activated, |1⟩ → activated",
        ]),
    ),
    WorkspaceTemplate(
        id="qnn",
        title="QNN Algorithm",
        kind="algorithm",
        description="Quantum Neural Network: 2-qubit variational circuit with RY/RZ layers and entanglement.",
        tags=["qnn", "qml", "variational", "difficulty:intermediate"],
        code="\n".join([
            "NOTE Quantum Neural Network — 2-qubit variational circuit",
            "",
            "INIT q0",
            "INIT q1",
            "",
            "LABEL Input encoding layer",
            "RY q0 0.7854",
            "RY q1 1.0472",
            "",
            "LABEL Hidden variational layer 1",
            "RZ q0 0.3927",
            "RZ q1 0.7854",
            "CNOT q0 q1",
            "",
            "LABEL Hidden variational layer 2",
            "RY q0 0.5236",
            "RY q1 0.2618",
            "CNOT q1 q0",
            "",
            "LABEL Output layer",
            "RZ q0 0.9817",
            "",
            "LABEL Readout",
            "MEASURE q0 BASIS Z",
        ]),
    ),
    WorkspaceTemplate(
        id="qaoa_maxcut",
        title="QAOA MaxCut",
        kind="algorithm",
        description=(
            "One-round QAOA for MaxCut on a 3-node triangle graph. "
            "ZZ-coupling cost layer and RX mixer."
        ),
        tags=["qaoa", "optimization", "maxcut", "difficulty:intermediate", "ref:pennylane"],
        code="\n".join([
            "NOTE QAOA MaxCut — 3-node triangle graph",
            "NOTE Ref: PennyLane QAOA",
            "",
            "INIT q0",
            "INIT q1",
            "INIT q2",
            "",
            "LABEL Initial superposition",
            "H q0",
            "H q1",
            "H q2",
            "",
            "LABEL Cost layer — ZZ coupling (γ = 0.8)",
            "NOTE Edge (q0, q1)",
            "CNOT q0 q1",
            "RZ q1 1.6",
            "CNOT q0 q1",
            "NOTE Edge (q1, q2)",
            "CNOT q1 q2",
            "RZ q2 1.6",
            "CNOT q1 q2",
            "NOTE Edge (q0, q2)",
            "CNOT q0 q2",
            "RZ q2 1.6",
            "CNOT q0 q2",
            "",
            "LABEL Mixer layer — RX (β = 0.5)",
            "RX q0 1.0",
            "RX q1 1.0",
            "RX q2 1.0",
            "",
            "LABEL Readout",
            "MEASURE q0 BASIS Z",
            "MEASURE q1 BASIS Z",
            "MEASURE q2 BASIS Z",
        ]),
    ),

    # ── Category 5: CHEMISTRY & SIMULATION ───────────────────────────────────
    WorkspaceTemplate(
        id="vqe_h2",
        title="VQE Ansatz (H₂ molecule)",
        kind="algorithm",
        description=(
            "Hardware-efficient VQE ansatz for the H₂ molecule Hamiltonian. "
            "RY → CNOT → RY layers at pre-optimized angles."
        ),
        tags=["vqe", "chemistry", "variational", "difficulty:intermediate", "ref:pennylane"],
        code="\n".join([
            "NOTE VQE ansatz for H₂ (hardware-efficient)",
            "NOTE Ref: PennyLane VQE tutorial",
            "",
            "INIT q0",
            "INIT q1",
            "",
            "LABEL Ansatz layer 1 — single-qubit rotations",
            "RY q0 0.5",
            "RY q1 -1.2",
            "",
            "LABEL Entangling layer",
            "CNOT q0 q1",
            "",
            "LABEL Ansatz layer 2 — single-qubit rotations",
            "RY q0 0.8",
            "RY q1 0.3",
            "",
            "LABEL Measure ⟨Z₀Z₁⟩ term",
            "MEASURE q0 BASIS Z",
            "MEASURE q1 BASIS Z",
            "",
            "NOTE In a full VQE:",
            "NOTE   1. A classical optimizer adjusts the RY angles",
            "NOTE   2. Multiple Pauli terms are measured (ZZ, ZI, IZ, XX)",
            "NOTE   3. The expectation values are summed to get ⟨H⟩",
        ]),
    ),
    WorkspaceTemplate(
        id="quantum_walk_1d",
        title="Quantum Walk (1D)",
        kind="algorithm",
        description="Discrete-time quantum walk on a line: coin qubit + position register with conditional shifts.",
        tags=["quantum-walk", "simulation", "difficulty:intermediate"],
        code="\n".join([
            "NOTE Discrete-time Quantum Walk — 1D line (3 steps)",
            "NOTE q0 = coin qubit, q1-q3 = 3-bit position register",
            "",
            "INIT q0",
            "INIT q1",
            "INIT q2",
            "INIT q3",
            "",
            "LABEL Start at position 0 = |000⟩",
            "NOTE (position register starts at |000⟩)",
            "",
            "LABEL Step 1: coin flip then conditional shift",
            "H q0",
            "CNOT q0 q3",
            "",
            "LABEL Step 2: coin flip then conditional shift",
            "H q0",
            "CNOT q0 q2",
            "CNOT q0 q3",
            "",
            "LABEL Step 3: coin flip then conditional shift",
            "H q0",
            "CNOT q0 q1",
            "CNOT q0 q2",
            "",
            "LABEL Readout — position distribution",
            "MEASURE q1 BASIS Z",
            "MEASURE q2 BASIS Z",
            "MEASURE q3 BASIS Z",
        ]),
    ),

    # ── Category 6: ERROR CORRECTION ─────────────────────────────────────────
    WorkspaceTemplate(
        id="qec_3qubit_repetition",
        title="QEC: 3-Qubit Repetition Code",
        kind="algorithm",
        description="Detects and corrects a single bit-flip error using a 3-qubit repetition code.",
        tags=["qec", "error-correction", "repetition-code", "difficulty:intermediate"],
        code="\n".join([
            "NOTE QEC: 3-Qubit Bit-Flip Repetition Code",
            "",
            "INIT q0 +",
            "INIT q1",
            "INIT q2",
            "",
            "LABEL Encode logical qubit into 3 physical qubits",
            "CNOT q0 q1",
            "CNOT q0 q2",
            "",
            "LABEL Simulate bit-flip error on q1",
            "NOTE (Comment out to test no-error case)",
            "X q1",
            "",
            "LABEL Syndrome measurement ancillas",
            "INIT q3",
            "INIT q4",
            "",
            "LABEL Parity check: q0 XOR q1",
            "CNOT q0 q3",
            "CNOT q1 q3",
            "",
            "LABEL Parity check: q1 XOR q2",
            "CNOT q1 q4",
            "CNOT q2 q4",
            "",
            "LABEL Measure syndromes",
            "MEASURE q3 BASIS Z",
            "MEASURE q4 BASIS Z",
            "",
            "NOTE Syndrome 10 → flip q0, 11 → flip q1, 01 → flip q2",
            "NOTE Apply correction then decode",
            "CNOT q0 q1",
            "CNOT q0 q2",
            "",
            "LABEL Readout logical qubit",
            "MEASURE q0 BASIS Z",
        ]),
    ),
    WorkspaceTemplate(
        id="qec_shor_9qubit",
        title="QEC: Shor's Nine-Qubit Code",
        kind="algorithm",
        description="Shor's 9-qubit code corrects arbitrary single-qubit errors (bit-flip + phase-flip).",
        tags=["qec", "error-correction", "shor-code", "difficulty:advanced"],
        code="\n".join([
            "NOTE Shor's 9-Qubit Code — corrects any single-qubit error",
            "NOTE Logical |0⟩_L = (|000⟩+|111⟩)^⊗3 / 2√2",
            "",
            "INIT q0",
            "INIT q1",
            "INIT q2",
            "INIT q3",
            "INIT q4",
            "INIT q5",
            "INIT q6",
            "INIT q7",
            "INIT q8",
            "",
            "LABEL Phase-flip code layer (outer code)",
            "H q0",
            "H q3",
            "H q6",
            "",
            "LABEL Bit-flip replication (inner repetition code)",
            "CNOT q0 q1",
            "CNOT q0 q2",
            "CNOT q3 q4",
            "CNOT q3 q5",
            "CNOT q6 q7",
            "CNOT q6 q8",
            "",
            "LABEL Simulate single phase-flip error on q0",
            "Z q0",
            "",
            "LABEL Bit-flip syndrome: check groups",
            "INIT q9",
            "CNOT q0 q9",
            "CNOT q1 q9",
            "MEASURE q9 BASIS Z",
            "",
            "LABEL Phase syndrome: Hadamard then check groups",
            "H q0",
            "H q3",
            "H q6",
            "INIT q10",
            "CNOT q0 q10",
            "CNOT q3 q10",
            "MEASURE q10 BASIS Z",
            "",
            "NOTE Full correction would apply X or Z based on syndromes",
        ]),
    ),
]


BENCHMARKS = [
    WorkspaceBenchmarkProfile(
        id="ghz",
        label="GHZ",
        description="Entanglement fan-out benchmark inspired by MQT Bench GHZ-style families.",
        qubits=8,
        family="communication",
    ),
    WorkspaceBenchmarkProfile(
        id="qft",
        label="QFT",
        description="Fourier-style benchmark inspired by the MQT Bench QFT circuit family.",
        qubits=10,
        family="transform",
    ),
    WorkspaceBenchmarkProfile(
        id="grover",
        label="Grover",
        description="Search-style benchmark inspired by the MQT Bench Grover family.",
        qubits=8,
        family="search",
    ),
    WorkspaceBenchmarkProfile(
        id="qaoa",
        label="QAOA",
        description="Optimization-style benchmark inspired by the MQT Bench QAOA family.",
        qubits=10,
        family="optimization",
    ),
    WorkspaceBenchmarkProfile(
        id="vqe",
        label="VQE",
        description="Variational quantum eigensolver ansatz benchmark derived from PennyLane VQE demos.",
        qubits=8,
        family="variational",
    ),
    WorkspaceBenchmarkProfile(
        id="qpe",
        label="QPE",
        description="Quantum Phase Estimation benchmark derived from PennyLane QPE template.",
        qubits=8,
        family="estimation",
    ),
    WorkspaceBenchmarkProfile(
        id="wstate",
        label="W-State",
        description="W-state preparation benchmark — single-excitation superposition.",
        qubits=10,
        family="communication",
    ),
    WorkspaceBenchmarkProfile(
        id="dj",
        label="Deutsch-Jozsa",
        description="Deutsch-Jozsa algorithm benchmark with balanced oracle.",
        qubits=10,
        family="decision",
    ),
]


def list_benchmark_profiles() -> list[WorkspaceBenchmarkProfile]:
    return BENCHMARKS


def get_workspace_catalog() -> WorkspaceCatalogResponse:
    return WorkspaceCatalogResponse(
        syntax=SYNTAX_REFERENCE,
        templates=TEMPLATES,
        benchmarks=BENCHMARKS,
        architecture_notes=[
            "Frontend parsing is kept in TypeScript so the editor can flag syntax errors before a network call.",
            "Backend execution owns the runtime state machine, measurements, transport events, and benchmark orchestration.",
            "Benchmarks run on the built-in _MiniSV pure-Python statevector engine — zero external dependencies required.",
            "Benchmark circuit families are inspired by MQT Bench and PennyLane templates.",
        ],
    )
